export const GET_ERRORS = "GET_ERRORS";
export const GET_PERSONS = "GET_PERSONS";
export const GET_PERSON = "GET_PERSON";

export const GET_BOOKS = "GET_BOOKS";
export const GET_BOOK = "GET_BOOK";


export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_PENDING_ERROR = "USER_PENDING_ERROR";
export const UPDATE_BOOK_STATUS = "UPDATE_BOOK_STATUS";

export const ADD_BOOKS_ERROR = "ADD_BOOKS_ERROR";
export const UPDATE_ERROR_STATUS = "UPDATE_ERROR_STATUS";

export const GET_USER_DELETE_ERRORS = "GET_USER_DELETE_ERRORS"
